### ISSUE TITLE
小程序用不了呀 方便留个联系方式吗

### ISSUE THREAD

**Issue by Percxxx** [leochan2017/zgjm#5]

**Comment by Percxxx** [comment]
![image](https://user-images.githubusercontent.com/95582197/144875165-957603a0-13c3-43be-9591-0c15329d4e4a.png)
![image](https://user-images.githubusercontent.com/95582197/144875197-1de1ab6a-1819-4dcb-a7dc-9eb44f8ebe82.png)
![image](https://user-images.githubusercontent.com/95582197/144875214-b78bd0c8-af10-4810-b308-ed0e38b6df6b.png)
这些里面都没有内容，是要用后台数据库吗

**Comment by leochan2017** [comment]
> ![image](https://user-images.githubusercontent.com/95582197/144875165-957603a0-13c3-43be-9591-0c15329d4e4a.png) ![image](https://user-images.githubusercontent.com/95582197/144875197-1de1ab6a-1819-4dcb-a7dc-9eb44f8ebe82.png) ![image](https://user-images.githubusercontent.com/95582197/144875214-b78bd0c8-af10-4810-b308-ed0e38b6df6b.png) 这些里面都没有内容，是要用后台数据库吗

数据都在本地
